### ISSUE TITLE
Comments are transferred to the Destination text after merging

### ISSUE THREAD

**Issue by SalitaNgDiyos** [rubiot/iBibliaMergeTool#7]
I successfully merged 2 projects. What I did was only copy the destination text of project A to project B. But after the merge, I noticed that the comments from project A went to the Destination text of project B as well even though I didn't select the comments button before merging.

**Comment by SalitaNgDiyos** [comment]
Here's more detail. 
*This only happens when the destination text is not selected.
*The comments appear at the end of the verse text as if its part of the verse and not just a note.

**Comment by rubiot** [comment]
I can't reproduce this here. I must be missing something.

**Comment by SalitaNgDiyos** [comment]
I think the problem doesn't occur in theWord but only in MySword. So, this is a MySword issue I think.
