### ISSUE TITLE
Import ALL range function

### ISSUE THREAD

**Issue by SalitaNgDiyos** [rubiot/iBibliaMergeTool#8]
Is there a command that will import all destination text, and/or source text, and/or association and/or comments from one project to another? It's like disabling the filter/range function all together during the merging.

**Comment by rubiot** [comment]
Sure, you can use "*" on the filter, but what's the point? You'll end up with the two identical projects - you can do the same with Ctrl+C, Ctrl+V on Windows Explorer.

**Comment by SalitaNgDiyos** [comment]
No, the function gives me the option to not import the associations, or the source text, or the destination text, or comments for the entire project. That is how I see it. So I can have different project versions depending on the absence or presence of those fields. Like for example: if I need to make 2 versions of MySword for Android modules, one with Tags and another one without Tags. They locked the toggle for strongs numbers unless you pay them at least $50.

**Comment by rubiot** [comment]
You're right! Sorry... Anyway, use `*` for the basic filter or `.` for the advanced.

**Comment by SalitaNgDiyos** [comment]
No problem, bro. Thanks for that info! You know since I got your Greek Interlinear, I've been doing some final touches on my translation and I feel more comfortable after doing this better than only using the tagged KJV. It's really a big help. I'm also going to use this tool to import the new revision into my untagged .bib project.
